### PR TITLE
Create: add deployments metadata

### PR DESCRIPTION
**Pull request by 0xGabi**

### CODE REVIEW

**Comment by nivida** [comment]
Do we really need those ABI's in the repo? especially for the localhost?

**Comment by 0xGabi** [comment]
These are the metadata generated by the `hardhay-deploy` plugin. I think they are valuable as they have the latests ABIs deployed to the different networks. But you are right we can probably skip localhost 👍

**Comment by izqui** [comment]
@nivida @0xGabi is this still needed? Let's close or merge

**Comment by novaknole** [comment]
Closing this, as it doesn't matter if the repo stores deployment files or not. Each time deploy script is run, it uses `deterministicDeployment` which means even if the deployment json files are not stored, it still creates the same ones.

**Pull request closed without merging**
