### PR TITLE
govern-core: check container execution time is valid on GovernQueue#resolve()

### PR DESCRIPTION
**Pull request by sohkai**
Nice catch, @nivida!

### CODE REVIEW

**Review by nivida — APPROVED** [review]

**Comment by izqui** [comment]
I might be missing something, but this was intentional.

After the resolver has made a final ruling, there's no reason to keep waiting since the container cannot be challenged more than once. Due to this, we assume that it can be immediately executed.

**Comment by nivida** [comment]
@izqui Our point was that the configured execution delay does no longer work as expected without checking it in the resolve method of the ``GovernQueue``. From my perspective and also from Marc should the voting get re-scheduled instead of executing it. This to keep the delay some users probably will count on (e.g.: "let me check that later"). And that someone can challenge for example another part of the voting. One will probably challenge the proof and another one the included actions idk.

I'm currently not 100% sure about the internals of the court used to resolve a dispute but is there 100% proof that a resolved dispute always will be correct? :-)

**Comment by izqui** [comment]
Thanks for the context, I still think that this delay is not needed since we should only allow one dispute, otherwise you can DOS this with ongoing challenges.

If an action is approved then it should be executable immediately, even if the evidence provided for the challenge is for one small part, guardians should always check the validity of the entire payload.

**Comment by nivida** [comment]
Sounds reasonable to me! Thanks for your input, Jorge! I will close this PR.

**Comment by marcvi1a** [comment]
@izqui I did not understand your response. Let me write the use case again: 

Disputable delay is 7 days, so users count on having a full week to review any action that's going to move on-cain.

Vote on a new action actually passes and goes into the queue. It's day 1 and someone challenges the action. The dispute is resolved in 24 hours, the claim is bad and the action must go on. So we're now in day 2 and the action has been resolved, should it be already implemented on-chain? That would "speed up" the process and cut the disputable delay from 7 days down to 2. Perhaps some users are no in favor of that action and would like to sell their tokens, for which they're counting on having 7 days as usual.

Therefore I think the original 7 days should be respected. I would propose for that action to move back to the queue in order to be implemented on-chain in 5 days time. It could be marked as already revised so no-one else can open a dispute.

**Comment by izqui** [comment]
I understand your point, but once it is challenged, guardians shouldn't just look at what the challenger claims but whether the entire action is valid.

Regardless of this wait, actions can only be challenged once in the code so during this additional waiting period it couldn't be re-challenged as it currently stands.

**Comment by marcvi1a** [comment]
I agree actions can only be challenged once. But to challenge an action should never be a mechanism to speed up implementation of that action. That's why the action needs to go back to the queue, and get implemented only after the delay period has concluded.

**Pull request closed without merging**
